name: Reproduce Non-Deterministic Hoisting

on:
  workflow_dispatch:

jobs:
  test-hoisting:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, macos-latest, windows-latest]
        attempt: [1, 2, 3]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.1
          
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
          
      - name: Test hoisting determinism (${{ matrix.os }} - attempt ${{ matrix.attempt }})
        shell: bash
        run: |
          chmod +x test.sh
          ./test.sh 200
        continue-on-error: true
        
      - name: Report results
        if: failure()
        run: |
          echo "::warning::Non-deterministic hoisting detected on ${{ matrix.os }} (attempt ${{ matrix.attempt }})"
          echo "Bug reproduced successfully on ${{ runner.os }}!"