name: Reproduce Non-Deterministic Hoisting

on:
  workflow_dispatch:

jobs:
  test-hoisting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        attempt: [1, 2, 3]
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 10.11.1
          
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Test hoisting determinism (attempt ${{ matrix.attempt }})
        run: |
          chmod +x test.sh
          ./test.sh 200
        continue-on-error: true
        
      - name: Report results
        if: failure()
        run: |
          echo "::warning::Non-deterministic hoisting detected in attempt ${{ matrix.attempt }}"
          echo "Bug reproduced successfully!"